
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


import junit.framework.TestCase;
import java.util.Random;




/**
 * Performs Validation Test for url validations.
 *
 * @version $Revision: 1128446 $ $Date: 2011-05-27 13:29:27 -0700 (Fri, 27 May 2011) $
 */
public class UrlValidatorTest extends TestCase {

   private boolean printStatus = false;
   private boolean printIndex = false;//print index that indicates current scheme,host,port,path, query test were using.

   public UrlValidatorTest(String testName) {
      super(testName);
   }

   public void testManualTest()
   {
      System.out.println("\n" + "\n" + "********************* Start Manual test *********************" + "\n");
      String[] schemes = {"http","https"};
      UrlValidator urlValidator = new UrlValidator(schemes);
      System.out.println("Manual Test 1 - http://www.google.com, http/http scheme");
      if (urlValidator.isValid("http://www.google.com")) {
         System.out.println("Manual Test 1 - Pass (Returned Valid)");
      } else {
         System.out.println("Manual Test 1 - Fail (Returned Invalid)");
      }
      System.out.println("Manual Test 2 - http://www.google.com, default scheme");
      UrlValidator urlValidator2 = new UrlValidator();
      if (urlValidator2.isValid("http://www.google.com")) {
         System.out.println("Manual Test 2 - Pass (Returned Valid)" );
      } else {
         System.out.println("Manual Test 2 - Fail (Returned Invalid)");
      }
      System.out.println("Manual Test 3 - http://www.google.com, ALLOW_ALL scheme");
      UrlValidator urlValidator3 = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      if (urlValidator3.isValid("http://www.google.com")) {
         System.out.println("Manual Test 3 - Pass (Returned Valid)");
      } else {
         System.out.println("Manual Test 3 - Fail (Returned Invalid)");
      }
      System.out.println("Manual Test 4 - http://kljadklualdfsdlfiadsf, ALLOW_ALL scheme");
      if (urlValidator3.isValid("http://kljadklualdfsdlfiadsf")) {
         System.out.println("Manual Test 4 - Fail (Returned Valid)");
      } else {
         System.out.println("Manual Test 4 - Pass (Returned Invalid)");
      }
      UrlValidator urlValidator4 = new UrlValidator();
      System.out.println("Manual Test 5 - https://www.google.com/, default scheme");
      if (urlValidator4.isValid("https://www.google.com/")) {
         System.out.println("Manual Test 5 - Pass (Returned Valid)");
      } else {
         System.out.println("Manual Test 5 - Pass (Returned Invalid)");
      }
      UrlValidator urlValidator5 = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      System.out.println("Manual Test 6 - http://kljadklualdfsdlfiadsf, ALLOW_ALL scheme");
      if (urlValidator5.isValid("http://kljadklualdfsdlfiadsf")) {
         System.out.println("Manual Test 6 - Fail (Returned Valid)");
      } else {
         System.out.println("Manual Test 6 - Pass (Returned Invalid)");
      }

      System.out.println("\n" + "********************* End Manual test *********************");
   }


   public void testschemePartition()
   {
      System.out.println("\n" + "\n" + "********************* Start Scheme Partition test *********************");
      UrlValidator urlVal = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      String[] validDomains= {"http://www.google.com","https://www.google.com", "ftp://www.google.com" ,
              "maps://www.google.com"};
      String[] invalidDomains= {"hptt://www.google.com","xttps://www.google.com", "ztr://www.google.com" ,
              "kansas://www.google.com"};

      System.out.println("\n"  + "               **** Good Scheme test ****");
      for (String v: validDomains) {
         try {
            if (urlVal.isValid(v) == true) {
               System.out.println("Scheme Test for " + v + " passed (Returned Valid)");
            } else {
               System.out.println("Scheme Test for " + v + " failed (Returned Invalid)");
            }
         } catch (Error e) {
            System.out.println("Scheme Test for " + v + " THREW AN EXCEPTION ERROR!!!");
         }
      }
      System.out.println("\n"  + "               **** Bad Scheme test ****");
      for (String i: invalidDomains) {
         try {
            if (urlVal.isValid(i) == false) {
               System.out.println("Scheme Test for " + i + " passed (Returned Invalid)");
            } else {
               System.out.println("Scheme Test for " + i + " failed (Returned Valid)");
            }
         } catch (Error e) {
            System.out.println("Scheme Test for " + i + " THREW AN EXCEPTION ERROR!!!");
         }
      }

      System.out.println("\n" + "********************* End Scheme Partition test *********************");

   }

   public void testdeliminatorsPartition()
   {
      System.out.println("\n" + "\n" + "********************* Start Deliminator Partition test *********************");
      UrlValidator urlVal = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      String[] validDeliminators= {"http://www.google.com","www.google.com"};
      String[] invalidDeliminators= {"http:/www.google.com" , "http//www.google.com" , "http/:/www.google.com"
              ,"http:?/www.google.com", "http|//www.google.com"};
      System.out.println("\n"  +   "               **** Good Deliminator test ****");
      for (String v: validDeliminators) {
         try {
            if (urlVal.isValid(v) == true) {
               System.out.println("Deliminator Test for " + v + " passed (Returned Valid)");
            } else {
               System.out.println("Deliminator Test for " + v + " failed (Returned Invalid)");
            }
         } catch (Error e) {
            System.out.println("Deliminator Test for " + v + " THREW AN EXCEPTION ERROR!!!");
         }
      }
      System.out.println("\n"  + "               **** Bad Deliminator test ****");
      for (String i: invalidDeliminators) {
         try {
            if (urlVal.isValid(i) == false) {
               System.out.println("Deliminator Test for " + i + " passed (Returned Invalid)");
            } else {
               System.out.println("Deliminator Test for " + i + " failed (Returned Valid)");
            }
         } catch (Error e) {
            System.out.println("Deliminator Test for " + i + " THREW AN EXCEPTION ERROR!!!");
         }
      }

      System.out.println("\n" + "********************* End Deliminator Partition test *********************");

   }

   public void testportsPartition()
   {
      System.out.println("\n" + "\n" + "********************* Start Port Partition test *********************");
      UrlValidator urlVal = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      String[] validPorts= {"http://www.google.com:0","http://www.google.com:128", "http://www.google.com:255"};
      String[] invalidPorts= {"http://www.google.com:-1" , "http://www.google.com:" , "http://www.google.com:ok"
              ,"http://www.google.com:256", "http://www.google.com://"};
      System.out.println("\n"  + "               **** Good Port Partition test ****");
      for (String v: validPorts) {
         try {
            if (urlVal.isValid(v) == true) {
               System.out.println("Port Test for " + v + " passed (Returned Valid)");
            } else {
               System.out.println("Port Test for " + v + " failed (Returned Invalid)");
            }
         } catch (Error e) {
            System.out.println("Port Test for " + v + " THREW AN EXCEPTION ERROR!!!");
         }
      }
      System.out.println("\n"  + "               **** Bad Port Partition test ****");
      for (String i: invalidPorts) {
         try {
            if (urlVal.isValid(i) == false) {
               System.out.println("Port Test for " + i + " passed (Returned Invalid)");
            } else {
               System.out.println("Port Test for " + i + " failed (Returned Valid)");
            }
         } catch (Error e) {
            System.out.println("Port Test for " + i + " THREW AN EXCEPTION ERROR!!!");
         }
      }

      System.out.println("\n" + "********************* End Port Partition test *********************");

   }

   public void testpathsPartition()
   {
      System.out.println("\n" + "\n" + "********************* Start Path Partition test *********************");
      UrlValidator urlVal = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);
      String[] validPaths= {"http://www.google.com/","http://www.google.com//", "http://www.google.com/abcd",
              "http://www.google.com/abcd.efgh", "http://www.google.com/abcd/efgh"};
      String[] invalidPaths= {"http://www.google.com///" , "http://www.google.com\\" , "http://www.google.com\\\\"
              ,"http://www.google.com:-4"};
      System.out.println("\n"  + "               **** Good Path Partition test ****");
      for (String v: validPaths) {
         try {
            if (urlVal.isValid(v) == true) {
               System.out.println("Path Test for " + v + " passed (Returned Valid)");
            } else {
               System.out.println("Path Test for " + v + " failed (Returned Invalid)");
            }
         } catch (Error e) {
            System.out.println("Path Test for " + v + " THREW AN EXCEPTION ERROR!!!");
         }
      }
      System.out.println("\n"  + "               **** Bad Path Partition test ****");
      for (String i: invalidPaths) {
         try {
            if (urlVal.isValid(i) == false) {
               System.out.println("Path Test for " + i + " passed (Returned Invalid)");
            } else {
               System.out.println("Path Test for " + i + " failed (Returned Valid)");
            }
         } catch (Error e) {
            System.out.println("Path Test for " + i + " THREW AN EXCEPTION ERROR!!!");
         }
      }

      System.out.println("\n" + "********************* End Path Partition test *********************");

   }


   public void testIsValid() {
      UrlValidator urlVal = new UrlValidator(null, null, UrlValidator.ALLOW_ALL_SCHEMES);

      Random rand = new Random();


   };

   ResultPair[] testIPNumbers = {
           new ResultPair("0",true),
           new ResultPair("128",true),
           new ResultPair("255",true),
           new ResultPair("-128",false),
           new ResultPair("256",false),
   };

   ResultPair[] testPorts = {
           new ResultPair("", true),
           new ResultPair(":-1", false),
           new ResultPair(":0", true),
           new ResultPair(":32818", true),
           new ResultPair(":65635",false),
           new ResultPair(":65536",false)
   };

   ResultPair[] testUrlDeliminator = {
           new ResultPair("://",true),
           new ResultPair(":/",false),
           new ResultPair("|:|",false),
           new ResultPair("//:",false),
           new ResultPair("/:/",false),
           new ResultPair("//",false),
           new ResultPair("/|:",false),
           new ResultPair("//?",false),
           new ResultPair("?|:",false),
           new ResultPair(":",false),
   };

   ResultPair[] testUrlScheme = {
           new ResultPair("",true),
           new ResultPair("aaa",true),
           new ResultPair("aaas",true),
           new ResultPair("about",true),
           new ResultPair("acap",true),
           new ResultPair("acct",true),
           new ResultPair("acr",true),
           new ResultPair("adiumxtra",true),
           new ResultPair("afp",true),
           new ResultPair("afs",true),
           new ResultPair("aim",true),
           new ResultPair("appdata",true),
           new ResultPair("apt",true),
           new ResultPair("attachment",true),
           new ResultPair("aw",true),
           new ResultPair("barion",true),
           new ResultPair("beshare",true),
           new ResultPair("bitcoin",true),
           new ResultPair("bitcoincash",true),
           new ResultPair("blob",true),
           new ResultPair("bolo",true),
           new ResultPair("browserext",true),
           new ResultPair("calculator",true),
           new ResultPair("callto",true),
           new ResultPair("cap",true),
           new ResultPair("chrome",true),
           new ResultPair("chrome-extension",true),
           new ResultPair("cid",true),
           new ResultPair("coap",true),
           new ResultPair("coap+tcp",true),
           new ResultPair("coap+ws",true),
           new ResultPair("coaps",true),
           new ResultPair("coaps+tcp",true),
           new ResultPair("coaps+ws",true),
           new ResultPair("com-eventbrite-attendee",true),
           new ResultPair("content",true),
           new ResultPair("conti",true),
           new ResultPair("crid",true),
           new ResultPair("cvs",true),
           new ResultPair("data",true),
           new ResultPair("dav",true),
           new ResultPair("diaspora",true),
           new ResultPair("dict",true),
           new ResultPair("did",true),
           new ResultPair("dis",true),
           new ResultPair("dlna-playcontainer",true),
           new ResultPair("dlna-playsingle",true),
           new ResultPair("dns",true),
           new ResultPair("dntp",true),
           new ResultPair("dtn",true),
           new ResultPair("dvb",true),
           new ResultPair("ed2k",true),
           new ResultPair("elsi",true),
           new ResultPair("example",true),
           new ResultPair("facetime",true),
           new ResultPair("fax",true),
           new ResultPair("feed",true),
           new ResultPair("feedready",true),
           new ResultPair("file",true),
           new ResultPair("filesystem",true),
           new ResultPair("finger",true),
           new ResultPair("fish",true),
           new ResultPair("ftp",true),
           new ResultPair("geo",true),
           new ResultPair("gg",true),
           new ResultPair("git",true),
           new ResultPair("gizmoproject",true),
           new ResultPair("go",true),
           new ResultPair("gopher",true),
           new ResultPair("graph",true),
           new ResultPair("gtalk",true),
           new ResultPair("h323",true),
           new ResultPair("ham",true),
           new ResultPair("hcap",true),
           new ResultPair("hcp",true),
           new ResultPair("http",true),
           new ResultPair("https",true),
           new ResultPair("hxxp",true),
           new ResultPair("hxxps",true),
           new ResultPair("hydrazone",true),
           new ResultPair("iax",true),
           new ResultPair("icap",true),
           new ResultPair("icon",true),
           new ResultPair("im",true),
           new ResultPair("imap",true),
           new ResultPair("info",true),
           new ResultPair("iotdisco",true),
           new ResultPair("ipn",true),
           new ResultPair("ipp",true),
           new ResultPair("ipps",true),
           new ResultPair("irc",true),
           new ResultPair("irc6",true),
           new ResultPair("ircs",true),
           new ResultPair("iris",true),
           new ResultPair("iris.beep",true),
           new ResultPair("iris.lwz",true),
           new ResultPair("iris.xpc",true),
           new ResultPair("iris.xpcs",true),
           new ResultPair("isostore",true),
           new ResultPair("itms",true),
           new ResultPair("jabber",true),
           new ResultPair("jar",true),
           new ResultPair("jms",true),
           new ResultPair("keyparc",true),
           new ResultPair("lastfm",true),
           new ResultPair("ldap",true),
           new ResultPair("ldaps",true),
           new ResultPair("lvlt",true),
           new ResultPair("magnet",true),
           new ResultPair("mailserver",true),
           new ResultPair("mailto",true),
           new ResultPair("maps",true),
           new ResultPair("market",true),
           new ResultPair("message",true),
           new ResultPair("microsoft.windows.camera",true),
           new ResultPair("microsoft.windows.camera.multipicker",true),
           new ResultPair("microsoft.windows.camera.picker",true),
           new ResultPair("mid",true),
           new ResultPair("mms",true),
           new ResultPair("modem",true),
           new ResultPair("mongodb",true),
           new ResultPair("moz",true),
           new ResultPair("ms-access",true),
           new ResultPair("ms-browser-extension",true),
           new ResultPair("ms-calculator",true),
           new ResultPair("ms-drive-to",true),
           new ResultPair("ms-enrollment",true),
           new ResultPair("ms-excel",true),
           new ResultPair("ms-eyecontrolspeech",true),
           new ResultPair("ms-gamebarservices",true),
           new ResultPair("ms-gamingoverlay",true),
           new ResultPair("ms-getoffice",true),
           new ResultPair("ms-help",true),
           new ResultPair("ms-infopath",true),
           new ResultPair("ms-inputapp",true),
           new ResultPair("ms-lockscreencomponent-config",true),
           new ResultPair("ms-media-stream-id",true),
           new ResultPair("ms-mixedrealitycapture",true),
           new ResultPair("ms-officeapp",true),
           new ResultPair("ms-people",true),
           new ResultPair("ms-project",true),
           new ResultPair("ms-powerpoint",true),
           new ResultPair("ms-publisher",true),
           new ResultPair("ms-restoretabcompanion",true),
           new ResultPair("ms-screenclip",true),
           new ResultPair("ms-screensketch",true),
           new ResultPair("ms-search",true),
           new ResultPair("ms-search-repair",true),
           new ResultPair("ms-secondary-screen-controller",true),
           new ResultPair("ms-secondary-screen-setup",true),
           new ResultPair("ms-settings",true),
           new ResultPair("ms-settings-airplanemode",true),
           new ResultPair("ms-settings-bluetooth",true),
           new ResultPair("ms-settings-camera",true),
           new ResultPair("ms-settings-cellular",true),
           new ResultPair("ms-settings-cloudstorage",true),
           new ResultPair("ms-settings-connectabledevices",true),
           new ResultPair("ms-settings-displays-topology",true),
           new ResultPair("ms-settings-emailandaccounts",true),
           new ResultPair("ms-settings-language",true),
           new ResultPair("ms-settings-location",true),
           new ResultPair("ms-settings-lock",true),
           new ResultPair("ms-settings-nfctransactions",true),
           new ResultPair("ms-settings-notifications",true),
           new ResultPair("ms-settings-power",true),
           new ResultPair("ms-settings-privacy",true),
           new ResultPair("ms-settings-proximity",true),
           new ResultPair("ms-settings-screenrotation",true),
           new ResultPair("ms-settings-wifi",true),
           new ResultPair("ms-settings-workplace",true),
           new ResultPair("ms-spd",true),
           new ResultPair("ms-sttoverlay",true),
           new ResultPair("ms-transit-to",true),
           new ResultPair("ms-useractivityset",true),
           new ResultPair("ms-virtualtouchpad",true),
           new ResultPair("ms-visio",true),
           new ResultPair("ms-walk-to",true),
           new ResultPair("ms-whiteboard",true),
           new ResultPair("ms-whiteboard-cmd",true),
           new ResultPair("ms-word",true),
           new ResultPair("msnim",true),
           new ResultPair("msrp",true),
           new ResultPair("msrps",true),
           new ResultPair("mtqp",true),
           new ResultPair("mumble",true),
           new ResultPair("mupdate",true),
           new ResultPair("mvn",true),
           new ResultPair("news",true),
           new ResultPair("nfs",true),
           new ResultPair("ni",true),
           new ResultPair("nih",true),
           new ResultPair("nntp",true),
           new ResultPair("notes",true),
           new ResultPair("ocf",true),
           new ResultPair("oid",true),
           new ResultPair("onenote",true),
           new ResultPair("onenote-cmd",true),
           new ResultPair("opaquelocktoken",true),
           new ResultPair("openpgp4fpr",true),
           new ResultPair("pack",true),
           new ResultPair("palm",true),
           new ResultPair("paparazzi",true),
           new ResultPair("pkcs11",true),
           new ResultPair("platform",true),
           new ResultPair("pop",true),
           new ResultPair("pres",true),
           new ResultPair("prospero",true),
           new ResultPair("proxy",true),
           new ResultPair("pwid",true),
           new ResultPair("psyc",true),
           new ResultPair("qb",true),
           new ResultPair("query",true),
           new ResultPair("redis",true),
           new ResultPair("rediss",true),
           new ResultPair("reload",true),
           new ResultPair("res",true),
           new ResultPair("resource",true),
           new ResultPair("rmi",true),
           new ResultPair("rsync",true),
           new ResultPair("rtmfp",true),
           new ResultPair("rtmp",true),
           new ResultPair("rtsp",true),
           new ResultPair("rtsps",true),
           new ResultPair("rtspu",true),
           new ResultPair("secondlife",true),
           new ResultPair("service",true),
           new ResultPair("session",true),
           new ResultPair("sftp",true),
           new ResultPair("sgn",true),
           new ResultPair("shttp",true),
           new ResultPair("sieve",true),
           new ResultPair("simpleledger",true),
           new ResultPair("sip",true),
           new ResultPair("sips",true),
           new ResultPair("skype",true),
           new ResultPair("smb",true),
           new ResultPair("sms",true),
           new ResultPair("smtp",true),
           new ResultPair("snews",true),
           new ResultPair("snmp",true),
           new ResultPair("soap.beep",true),
           new ResultPair("soap.beeps",true),
           new ResultPair("soldat",true),
           new ResultPair("spiffe",true),
           new ResultPair("spotify",true),
           new ResultPair("ssh",true),
           new ResultPair("steam",true),
           new ResultPair("stun",true),
           new ResultPair("stuns",true),
           new ResultPair("submit",true),
           new ResultPair("svn",true),
           new ResultPair("tag",true),
           new ResultPair("teamspeak",true),
           new ResultPair("tel",true),
           new ResultPair("teliaeid",true),
           new ResultPair("telnet",true),
           new ResultPair("tftp",true),
           new ResultPair("things",true),
           new ResultPair("thismessage",true),
           new ResultPair("tip",true),
           new ResultPair("tn3270",true),
           new ResultPair("tool",true),
           new ResultPair("turn",true),
           new ResultPair("turns",true),
           new ResultPair("tv",true),
           new ResultPair("udp",true),
           new ResultPair("unreal",true),
           new ResultPair("urn",true),
           new ResultPair("ut2004",true),
           new ResultPair("v-event",true),
           new ResultPair("vemmi",true),
           new ResultPair("ventrilo",true),
           new ResultPair("videotex",true),
           new ResultPair("vnc",true),
           new ResultPair("view-source",true),
           new ResultPair("wais",true),
           new ResultPair("webcal",true),
           new ResultPair("wpid",true),
           new ResultPair("ws",true),
           new ResultPair("wss",true),
           new ResultPair("wtai",true),
           new ResultPair("wyciwyg",true),
           new ResultPair("xcon",true),
           new ResultPair("xcon-userid",true),
           new ResultPair("xfire",true),
           new ResultPair("xmlrpc.beep",true),
           new ResultPair("xmlrpc.beeps",true),
           new ResultPair("xmpp",true),
           new ResultPair("xri",true),
           new ResultPair("ymsgr",true),
           new ResultPair("z39.50",true),
           new ResultPair("z39.50r",true),
           new ResultPair("z39.50s",true)
   };

// All Valid ICANN domain extensions http://data.iana.org/TLD/tlds-alpha-by-domain.tx
   ResultPair[] testUrlExt  = {
        new ResultPair("aaa",           true),
        new ResultPair("aarp",true),
        new ResultPair("abarth",true),
        new ResultPair("abb",true),
        new ResultPair("abbott",true),
        new ResultPair("abbvie",true),
        new ResultPair("abc",true),
        new ResultPair("able",true),
        new ResultPair("abogado",true),
        new ResultPair("abudhabi",true),
        new ResultPair("ac",true),
        new ResultPair("academy",true),
        new ResultPair("accenture",true),
        new ResultPair("accountant",true),
        new ResultPair("accountants",true),
        new ResultPair("aco",true),
        new ResultPair("active",true),
        new ResultPair("actor",true),
        new ResultPair("ad",true),
        new ResultPair("adac",true),
        new ResultPair("ads",true),
        new ResultPair("adult",true),
        new ResultPair("ae",true),
        new ResultPair("aeg",true),
        new ResultPair("aero",true),
        new ResultPair("aetna",true),
        new ResultPair("af",true),
        new ResultPair("afamilycompany",true),
        new ResultPair("afl",true),
        new ResultPair("africa",true),
        new ResultPair("ag",true),
        new ResultPair("agakhan",true),
        new ResultPair("agency",true),
        new ResultPair("ai",true),
        new ResultPair("aig",true),
        new ResultPair("aigo",true),
        new ResultPair("airbus",true),
        new ResultPair("airforce",true),
        new ResultPair("airtel",true),
        new ResultPair("akdn",true),
        new ResultPair("al",true),
        new ResultPair("alfaromeo",true),
        new ResultPair("alibaba",true),
        new ResultPair("alipay",true),
        new ResultPair("allfinanz",true),
        new ResultPair("allstate",true),
        new ResultPair("ally",true),
        new ResultPair("alsace",true),
        new ResultPair("alstom",true),
        new ResultPair("am",true),
        new ResultPair("americanexpress",true),
        new ResultPair("americanfamily",true),
        new ResultPair("amex",true),
        new ResultPair("amfam",true),
        new ResultPair("amica",true),
        new ResultPair("amsterdam",true),
        new ResultPair("analytics",true),
        new ResultPair("android",true),
        new ResultPair("anquan",true),
        new ResultPair("anz",true),
        new ResultPair("ao",true),
        new ResultPair("aol",true),
        new ResultPair("apartments",true),
        new ResultPair("app",true),
        new ResultPair("apple",true),
        new ResultPair("aq",true),
        new ResultPair("aquarelle",true),
        new ResultPair("ar",true),
        new ResultPair("arab",true),
        new ResultPair("aramco",true),
        new ResultPair("archi",true),
        new ResultPair("army",true),
        new ResultPair("arpa",true),
        new ResultPair("art",true),
        new ResultPair("arte",true),
        new ResultPair("as",true),
        new ResultPair("asda",true),
        new ResultPair("asia",true),
        new ResultPair("associates",true),
        new ResultPair("at",true),
        new ResultPair("athleta",true),
        new ResultPair("attorney",true),
        new ResultPair("au",true),
        new ResultPair("auction",true),
        new ResultPair("audi",true),
        new ResultPair("audible",true),
        new ResultPair("audio",true),
        new ResultPair("auspost",true),
        new ResultPair("author",true),
        new ResultPair("auto",true),
        new ResultPair("autos",true),
        new ResultPair("avianca",true),
        new ResultPair("aw",true),
        new ResultPair("aws",true),
        new ResultPair("ax",true),
        new ResultPair("axa",true),
        new ResultPair("az",true),
        new ResultPair("azure",true),
        new ResultPair("ba",true),
        new ResultPair("baby",true),
        new ResultPair("baidu",true),
        new ResultPair("banamex",true),
        new ResultPair("bananarepublic",true),
        new ResultPair("band",true),
        new ResultPair("bank",true),
        new ResultPair("bar",true),
        new ResultPair("barcelona",true),
        new ResultPair("barclaycard",true),
        new ResultPair("barclays",true),
        new ResultPair("barefoot",true),
        new ResultPair("bargains",true),
        new ResultPair("baseball",true),
        new ResultPair("basketball",true),
        new ResultPair("bauhaus",true),
        new ResultPair("bayern",true),
        new ResultPair("bb",true),
        new ResultPair("bbc",true),
        new ResultPair("bbt",true),
        new ResultPair("bbva",true),
        new ResultPair("bcg",true),
        new ResultPair("bcn",true),
        new ResultPair("bd",true),
        new ResultPair("be",true),
        new ResultPair("beats",true),
        new ResultPair("beauty",true),
        new ResultPair("beer",true),
        new ResultPair("bentley",true),
        new ResultPair("berlin",true),
        new ResultPair("best",true),
        new ResultPair("bestbuy",true),
        new ResultPair("bet",true),
        new ResultPair("bf",true),
        new ResultPair("bg",true),
        new ResultPair("bh",true),
        new ResultPair("bharti",true),
        new ResultPair("bi",true),
        new ResultPair("bible",true),
        new ResultPair("bid",true),
        new ResultPair("bike",true),
        new ResultPair("bing",true),
        new ResultPair("bingo",true),
        new ResultPair("bio",true),
        new ResultPair("biz",true),
        new ResultPair("bj",true),
        new ResultPair("black",true),
        new ResultPair("blackfriday",true),
        new ResultPair("blanco",true),
        new ResultPair("blockbuster",true),
        new ResultPair("blog",true),
        new ResultPair("bloomberg",true),
        new ResultPair("blue",true),
        new ResultPair("bm",true),
        new ResultPair("bms",true),
        new ResultPair("bmw",true),
        new ResultPair("bn",true),
        new ResultPair("bnl",true),
        new ResultPair("bnpparibas",true),
        new ResultPair("bo",true),
        new ResultPair("boats",true),
        new ResultPair("boehringer",true),
        new ResultPair("bofa",true),
        new ResultPair("bom",true),
        new ResultPair("bond",true),
        new ResultPair("boo",true),
        new ResultPair("book",true),
        new ResultPair("booking",true),
        new ResultPair("bosch",true),
        new ResultPair("bostik",true),
        new ResultPair("boston",true),
        new ResultPair("bot",true),
        new ResultPair("boutique",true),
        new ResultPair("box",true),
        new ResultPair("br",true),
        new ResultPair("bradesco",true),
        new ResultPair("bridgestone",true),
        new ResultPair("broadway",true),
        new ResultPair("broker",true),
        new ResultPair("brother",true),
        new ResultPair("brussels",true),
        new ResultPair("bs",true),
        new ResultPair("bt",true),
        new ResultPair("budapest",true),
        new ResultPair("bugatti",true),
        new ResultPair("build",true),
        new ResultPair("builders",true),
        new ResultPair("business",true),
        new ResultPair("buy",true),
        new ResultPair("buzz",true),
        new ResultPair("bv",true),
        new ResultPair("bw",true),
        new ResultPair("by",true),
        new ResultPair("bz",true),
        new ResultPair("bzh",true),
        new ResultPair("ca",true),
        new ResultPair("cab",true),
        new ResultPair("cafe",true),
        new ResultPair("cal",true),
        new ResultPair("call",true),
        new ResultPair("calvinklein",true),
        new ResultPair("cam",true),
        new ResultPair("camera",true),
        new ResultPair("camp",true),
        new ResultPair("cancerresearch",true),
        new ResultPair("canon",true),
        new ResultPair("capetown",true),
        new ResultPair("capital",true),
        new ResultPair("capitalone",true),
        new ResultPair("car",true),
        new ResultPair("caravan",true),
        new ResultPair("cards",true),
        new ResultPair("care",true),
        new ResultPair("career",true),
        new ResultPair("careers",true),
        new ResultPair("cars",true),
        new ResultPair("cartier",true),
        new ResultPair("casa",true),
        new ResultPair("case",true),
        new ResultPair("caseih",true),
        new ResultPair("cash",true),
        new ResultPair("casino",true),
        new ResultPair("cat",true),
        new ResultPair("catering",true),
        new ResultPair("catholic",true),
        new ResultPair("cba",true),
        new ResultPair("cbn",true),
        new ResultPair("cbre",true),
        new ResultPair("cbs",true),
        new ResultPair("cc",true),
        new ResultPair("cd",true),
        new ResultPair("ceb",true),
        new ResultPair("center",true),
        new ResultPair("ceo",true),
        new ResultPair("cern",true),
        new ResultPair("cf",true),
        new ResultPair("cfa",true),
        new ResultPair("cfd",true),
        new ResultPair("cg",true),
        new ResultPair("ch",true),
        new ResultPair("chanel",true),
        new ResultPair("channel",true),
        new ResultPair("charity",true),
        new ResultPair("chase",true),
        new ResultPair("chat",true),
        new ResultPair("cheap",true),
        new ResultPair("chintai",true),
        new ResultPair("christmas",true),
        new ResultPair("chrome",true),
        new ResultPair("chrysler",true),
        new ResultPair("church",true),
        new ResultPair("ci",true),
        new ResultPair("cipriani",true),
        new ResultPair("circle",true),
        new ResultPair("cisco",true),
        new ResultPair("citadel",true),
        new ResultPair("citi",true),
        new ResultPair("citic",true),
        new ResultPair("city",true),
        new ResultPair("cityeats",true),
        new ResultPair("ck",true),
        new ResultPair("cl",true),
        new ResultPair("claims",true),
        new ResultPair("cleaning",true),
        new ResultPair("click",true),
        new ResultPair("clinic",true),
        new ResultPair("clinique",true),
        new ResultPair("clothing",true),
        new ResultPair("cloud",true),
        new ResultPair("club",true),
        new ResultPair("clubmed",true),
        new ResultPair("cm",true),
        new ResultPair("cn",true),
        new ResultPair("co",true),
        new ResultPair("coach",true),
        new ResultPair("codes",true),
        new ResultPair("coffee",true),
        new ResultPair("college",true),
        new ResultPair("cologne",true),
        new ResultPair("com",true),
        new ResultPair("comcast",true),
        new ResultPair("commbank",true),
        new ResultPair("community",true),
        new ResultPair("company",true),
        new ResultPair("compare",true),
        new ResultPair("computer",true),
        new ResultPair("comsec",true),
        new ResultPair("condos",true),
        new ResultPair("construction",true),
        new ResultPair("consulting",true),
        new ResultPair("contact",true),
        new ResultPair("contractors",true),
        new ResultPair("cooking",true),
        new ResultPair("cookingchannel",true),
        new ResultPair("cool",true),
        new ResultPair("coop",true),
        new ResultPair("corsica",true),
        new ResultPair("country",true),
        new ResultPair("coupon",true),
        new ResultPair("coupons",true),
        new ResultPair("courses",true),
        new ResultPair("cr",true),
        new ResultPair("credit",true),
        new ResultPair("creditcard",true),
        new ResultPair("creditunion",true),
        new ResultPair("cricket",true),
        new ResultPair("crown",true),
        new ResultPair("crs",true),
        new ResultPair("cruise",true),
        new ResultPair("cruises",true),
        new ResultPair("csc",true),
        new ResultPair("cu",true),
        new ResultPair("cuisinella",true),
        new ResultPair("cv",true),
        new ResultPair("cw",true),
        new ResultPair("cx",true),
        new ResultPair("cy",true),
        new ResultPair("cymru",true),
        new ResultPair("cyou",true),
        new ResultPair("cz",true),
        new ResultPair("dabur",true),
        new ResultPair("dad",true),
        new ResultPair("dance",true),
        new ResultPair("data",true),
        new ResultPair("date",true),
        new ResultPair("dating",true),
        new ResultPair("datsun",true),
        new ResultPair("day",true),
        new ResultPair("dclk",true),
        new ResultPair("dds",true),
        new ResultPair("de",true),
        new ResultPair("deal",true),
        new ResultPair("dealer",true),
        new ResultPair("deals",true),
        new ResultPair("degree",true),
        new ResultPair("delivery",true),
        new ResultPair("dell",true),
        new ResultPair("deloitte",true),
        new ResultPair("delta",true),
        new ResultPair("democrat",true),
        new ResultPair("dental",true),
        new ResultPair("dentist",true),
        new ResultPair("desi",true),
        new ResultPair("design",true),
        new ResultPair("dev",true),
        new ResultPair("dhl",true),
        new ResultPair("diamonds",true),
        new ResultPair("diet",true),
        new ResultPair("digital",true),
        new ResultPair("direct",true),
        new ResultPair("directory",true),
        new ResultPair("discount",true),
        new ResultPair("discover",true),
        new ResultPair("dish",true),
        new ResultPair("diy",true),
        new ResultPair("dj",true),
        new ResultPair("dk",true),
        new ResultPair("dm",true),
        new ResultPair("dnp",true),
        new ResultPair("do",true),
        new ResultPair("docs",true),
        new ResultPair("doctor",true),
        new ResultPair("dodge",true),
        new ResultPair("dog",true),
        new ResultPair("doha",true),
        new ResultPair("domains",true),
        new ResultPair("dot",true),
        new ResultPair("download",true),
        new ResultPair("drive",true),
        new ResultPair("dtv",true),
        new ResultPair("dubai",true),
        new ResultPair("duck",true),
        new ResultPair("dunlop",true),
        new ResultPair("duns",true),
        new ResultPair("dupont",true),
        new ResultPair("durban",true),
        new ResultPair("dvag",true),
        new ResultPair("dvr",true),
        new ResultPair("dz",true),
        new ResultPair("earth",true),
        new ResultPair("eat",true),
        new ResultPair("ec",true),
        new ResultPair("eco",true),
        new ResultPair("edeka",true),
        new ResultPair("edu",true),
        new ResultPair("education",true),
        new ResultPair("ee",true),
        new ResultPair("eg",true),
        new ResultPair("email",true),
        new ResultPair("emerck",true),
        new ResultPair("energy",true),
        new ResultPair("engineer",true),
        new ResultPair("engineering",true),
        new ResultPair("enterprises",true),
        new ResultPair("epost",true),
        new ResultPair("epson",true),
        new ResultPair("equipment",true),
        new ResultPair("er",true),
        new ResultPair("ericsson",true),
        new ResultPair("erni",true),
        new ResultPair("es",true),
        new ResultPair("esq",true),
        new ResultPair("estate",true),
        new ResultPair("esurance",true),
        new ResultPair("et",true),
        new ResultPair("etisalat",true),
        new ResultPair("eu",true),
        new ResultPair("eurovision",true),
        new ResultPair("eus",true),
        new ResultPair("events",true),
        new ResultPair("everbank",true),
        new ResultPair("exchange",true),
        new ResultPair("expert",true),
        new ResultPair("exposed",true),
        new ResultPair("express",true),
        new ResultPair("extraspace",true),
        new ResultPair("fage",true),
        new ResultPair("fail",true),
        new ResultPair("fairwinds",true),
        new ResultPair("faith",true),
        new ResultPair("family",true),
        new ResultPair("fan",true),
        new ResultPair("fans",true),
        new ResultPair("farm",true),
        new ResultPair("farmers",true),
        new ResultPair("fashion",true),
        new ResultPair("fast",true),
        new ResultPair("fedex",true),
        new ResultPair("feedback",true),
        new ResultPair("ferrari",true),
        new ResultPair("ferrero",true),
        new ResultPair("fi",true),
        new ResultPair("fiat",true),
        new ResultPair("fidelity",true),
        new ResultPair("fido",true),
        new ResultPair("film",true),
        new ResultPair("final",true),
        new ResultPair("finance",true),
        new ResultPair("financial",true),
        new ResultPair("fire",true),
        new ResultPair("firestone",true),
        new ResultPair("firmdale",true),
        new ResultPair("fish",true),
        new ResultPair("fishing",true),
        new ResultPair("fit",true),
        new ResultPair("fitness",true),
        new ResultPair("fj",true),
        new ResultPair("fk",true),
        new ResultPair("flickr",true),
        new ResultPair("flights",true),
        new ResultPair("flir",true),
        new ResultPair("florist",true),
        new ResultPair("flowers",true),
        new ResultPair("fly",true),
        new ResultPair("fm",true),
        new ResultPair("fo",true),
        new ResultPair("foo",true),
        new ResultPair("food",true),
        new ResultPair("foodnetwork",true),
        new ResultPair("football",true),
        new ResultPair("ford",true),
        new ResultPair("forex",true),
        new ResultPair("forsale",true),
        new ResultPair("forum",true),
        new ResultPair("foundation",true),
        new ResultPair("fox",true),
        new ResultPair("fr",true),
        new ResultPair("free",true),
        new ResultPair("fresenius",true),
        new ResultPair("frl",true),
        new ResultPair("frogans",true),
        new ResultPair("frontdoor",true),
        new ResultPair("frontier",true),
        new ResultPair("ftr",true),
        new ResultPair("fujitsu",true),
        new ResultPair("fujixerox",true),
        new ResultPair("fun",true),
        new ResultPair("fund",true),
        new ResultPair("furniture",true),
        new ResultPair("futbol",true),
        new ResultPair("fyi",true),
        new ResultPair("ga",true),
        new ResultPair("gal",true),
        new ResultPair("gallery",true),
        new ResultPair("gallo",true),
        new ResultPair("gallup",true),
        new ResultPair("game",true),
        new ResultPair("games",true),
        new ResultPair("gap",true),
        new ResultPair("garden",true),
        new ResultPair("gb",true),
        new ResultPair("gbiz",true),
        new ResultPair("gd",true),
        new ResultPair("gdn",true),
        new ResultPair("ge",true),
        new ResultPair("gea",true),
        new ResultPair("gent",true),
        new ResultPair("genting",true),
        new ResultPair("george",true),
        new ResultPair("gf",true),
        new ResultPair("gg",true),
        new ResultPair("ggee",true),
        new ResultPair("gh",true),
        new ResultPair("gi",true),
        new ResultPair("gift",true),
        new ResultPair("gifts",true),
        new ResultPair("gives",true),
        new ResultPair("giving",true),
        new ResultPair("gl",true),
        new ResultPair("glade",true),
        new ResultPair("glass",true),
        new ResultPair("gle",true),
        new ResultPair("global",true),
        new ResultPair("globo",true),
        new ResultPair("gm",true),
        new ResultPair("gmail",true),
        new ResultPair("gmbh",true),
        new ResultPair("gmo",true),
        new ResultPair("gmx",true),
        new ResultPair("gn",true),
        new ResultPair("godaddy",true),
        new ResultPair("gold",true),
        new ResultPair("goldpoint",true),
        new ResultPair("golf",true),
        new ResultPair("goo",true),
        new ResultPair("goodyear",true),
        new ResultPair("goog",true),
        new ResultPair("google",true),
        new ResultPair("gop",true),
        new ResultPair("got",true),
        new ResultPair("gov",true),
        new ResultPair("gp",true),
        new ResultPair("gq",true),
        new ResultPair("gr",true),
        new ResultPair("grainger",true),
        new ResultPair("graphics",true),
        new ResultPair("gratis",true),
        new ResultPair("green",true),
        new ResultPair("gripe",true),
        new ResultPair("grocery",true),
        new ResultPair("group",true),
        new ResultPair("gs",true),
        new ResultPair("gt",true),
        new ResultPair("gu",true),
        new ResultPair("guardian",true),
        new ResultPair("gucci",true),
        new ResultPair("guge",true),
        new ResultPair("guide",true),
        new ResultPair("guitars",true),
        new ResultPair("guru",true),
        new ResultPair("gw",true),
        new ResultPair("gy",true),
        new ResultPair("hair",true),
        new ResultPair("hamburg",true),
        new ResultPair("hangout",true),
        new ResultPair("haus",true),
        new ResultPair("hbo",true),
        new ResultPair("hdfc",true),
        new ResultPair("hdfcbank",true),
        new ResultPair("health",true),
        new ResultPair("healthcare",true),
        new ResultPair("help",true),
        new ResultPair("helsinki",true),
        new ResultPair("here",true),
        new ResultPair("hermes",true),
        new ResultPair("hgtv",true),
        new ResultPair("hiphop",true),
        new ResultPair("hisamitsu",true),
        new ResultPair("hitachi",true),
        new ResultPair("hiv",true),
        new ResultPair("hk",true),
        new ResultPair("hkt",true),
        new ResultPair("hm",true),
        new ResultPair("hn",true),
        new ResultPair("hockey",true),
        new ResultPair("holdings",true),
        new ResultPair("holiday",true),
        new ResultPair("homedepot",true),
        new ResultPair("homegoods",true),
        new ResultPair("homes",true),
        new ResultPair("homesense",true),
        new ResultPair("honda",true),
        new ResultPair("honeywell",true),
        new ResultPair("horse",true),
        new ResultPair("hospital",true),
        new ResultPair("host",true),
        new ResultPair("hosting",true),
        new ResultPair("hot",true),
        new ResultPair("hoteles",true),
        new ResultPair("hotels",true),
        new ResultPair("hotmail",true),
        new ResultPair("house",true),
        new ResultPair("how",true),
        new ResultPair("hr",true),
        new ResultPair("hsbc",true),
        new ResultPair("ht",true),
        new ResultPair("hu",true),
        new ResultPair("hughes",true),
        new ResultPair("hyatt",true),
        new ResultPair("hyundai",true),
        new ResultPair("ibm",true),
        new ResultPair("icbc",true),
        new ResultPair("ice",true),
        new ResultPair("icu",true),
        new ResultPair("id",true),
        new ResultPair("ie",true),
        new ResultPair("ieee",true),
        new ResultPair("ifm",true),
        new ResultPair("ikano",true),
        new ResultPair("il",true),
        new ResultPair("im",true),
        new ResultPair("imamat",true),
        new ResultPair("imdb",true),
        new ResultPair("immo",true),
        new ResultPair("immobilien",true),
        new ResultPair("in",true),
        new ResultPair("inc",true),
        new ResultPair("industries",true),
        new ResultPair("infiniti",true),
        new ResultPair("info",true),
        new ResultPair("ing",true),
        new ResultPair("ink",true),
        new ResultPair("institute",true),
        new ResultPair("insurance",true),
        new ResultPair("insure",true),
        new ResultPair("int",true),
        new ResultPair("intel",true),
        new ResultPair("international",true),
        new ResultPair("intuit",true),
        new ResultPair("investments",true),
        new ResultPair("io",true),
        new ResultPair("ipiranga",true),
        new ResultPair("iq",true),
        new ResultPair("ir",true),
        new ResultPair("irish",true),
        new ResultPair("is",true),
        new ResultPair("iselect",true),
        new ResultPair("ismaili",true),
        new ResultPair("ist",true),
        new ResultPair("istanbul",true),
        new ResultPair("it",true),
        new ResultPair("itau",true),
        new ResultPair("itv",true),
        new ResultPair("iveco",true),
        new ResultPair("jaguar",true),
        new ResultPair("java",true),
        new ResultPair("jcb",true),
        new ResultPair("jcp",true),
        new ResultPair("je",true),
        new ResultPair("jeep",true),
        new ResultPair("jetzt",true),
        new ResultPair("jewelry",true),
        new ResultPair("jio",true),
        new ResultPair("jll",true),
        new ResultPair("jm",true),
        new ResultPair("jmp",true),
        new ResultPair("jnj",true),
        new ResultPair("jo",true),
        new ResultPair("jobs",true),
        new ResultPair("joburg",true),
        new ResultPair("jot",true),
        new ResultPair("joy",true),
        new ResultPair("jp",true),
        new ResultPair("jpmorgan",true),
        new ResultPair("jprs",true),
        new ResultPair("juegos",true),
        new ResultPair("juniper",true),
        new ResultPair("kaufen",true),
        new ResultPair("kddi",true),
        new ResultPair("ke",true),
        new ResultPair("kerryhotels",true),
        new ResultPair("kerrylogistics",true),
        new ResultPair("kerryproperties",true),
        new ResultPair("kfh",true),
        new ResultPair("kg",true),
        new ResultPair("kh",true),
        new ResultPair("ki",true),
        new ResultPair("kia",true),
        new ResultPair("kim",true),
        new ResultPair("kinder",true),
        new ResultPair("kindle",true),
        new ResultPair("kitchen",true),
        new ResultPair("kiwi",true),
        new ResultPair("km",true),
        new ResultPair("kn",true),
        new ResultPair("koeln",true),
        new ResultPair("komatsu",true),
        new ResultPair("kosher",true),
        new ResultPair("kp",true),
        new ResultPair("kpmg",true),
        new ResultPair("kpn",true),
        new ResultPair("kr",true),
        new ResultPair("krd",true),
        new ResultPair("kred",true),
        new ResultPair("kuokgroup",true),
        new ResultPair("kw",true),
        new ResultPair("ky",true),
        new ResultPair("kyoto",true),
        new ResultPair("kz",true),
        new ResultPair("la",true),
        new ResultPair("lacaixa",true),
        new ResultPair("ladbrokes",true),
        new ResultPair("lamborghini",true),
        new ResultPair("lamer",true),
        new ResultPair("lancaster",true),
        new ResultPair("lancia",true),
        new ResultPair("lancome",true),
        new ResultPair("land",true),
        new ResultPair("landrover",true),
        new ResultPair("lanxess",true),
        new ResultPair("lasalle",true),
        new ResultPair("lat",true),
        new ResultPair("latino",true),
        new ResultPair("latrobe",true),
        new ResultPair("law",true),
        new ResultPair("lawyer",true),
        new ResultPair("lb",true),
        new ResultPair("lc",true),
        new ResultPair("lds",true),
        new ResultPair("lease",true),
        new ResultPair("leclerc",true),
        new ResultPair("lefrak",true),
        new ResultPair("legal",true),
        new ResultPair("lego",true),
        new ResultPair("lexus",true),
        new ResultPair("lgbt",true),
        new ResultPair("li",true),
        new ResultPair("liaison",true),
        new ResultPair("lidl",true),
        new ResultPair("life",true),
        new ResultPair("lifeinsurance",true),
        new ResultPair("lifestyle",true),
        new ResultPair("lighting",true),
        new ResultPair("like",true),
        new ResultPair("lilly",true),
        new ResultPair("limited",true),
        new ResultPair("limo",true),
        new ResultPair("lincoln",true),
        new ResultPair("linde",true),
        new ResultPair("link",true),
        new ResultPair("lipsy",true),
        new ResultPair("live",true),
        new ResultPair("living",true),
        new ResultPair("lixil",true),
        new ResultPair("lk",true),
        new ResultPair("llc",true),
        new ResultPair("loan",true),
        new ResultPair("loans",true),
        new ResultPair("locker",true),
        new ResultPair("locus",true),
        new ResultPair("loft",true),
        new ResultPair("lol",true),
        new ResultPair("london",true),
        new ResultPair("lotte",true),
        new ResultPair("lotto",true),
        new ResultPair("love",true),
        new ResultPair("lpl",true),
        new ResultPair("lplfinancial",true),
        new ResultPair("lr",true),
        new ResultPair("ls",true),
        new ResultPair("lt",true),
        new ResultPair("ltd",true),
        new ResultPair("ltda",true),
        new ResultPair("lu",true),
        new ResultPair("lundbeck",true),
        new ResultPair("lupin",true),
        new ResultPair("luxe",true),
        new ResultPair("luxury",true),
        new ResultPair("lv",true),
        new ResultPair("ly",true),
        new ResultPair("ma",true),
        new ResultPair("macys",true),
        new ResultPair("madrid",true),
        new ResultPair("maif",true),
        new ResultPair("maison",true),
        new ResultPair("makeup",true),
        new ResultPair("man",true),
        new ResultPair("management",true),
        new ResultPair("mango",true),
        new ResultPair("map",true),
        new ResultPair("market",true),
        new ResultPair("marketing",true),
        new ResultPair("markets",true),
        new ResultPair("marriott",true),
        new ResultPair("marshalls",true),
        new ResultPair("maserati",true),
        new ResultPair("mattel",true),
        new ResultPair("mba",true),
        new ResultPair("mc",true),
        new ResultPair("mckinsey",true),
        new ResultPair("md",true),
        new ResultPair("me",true),
        new ResultPair("med",true),
        new ResultPair("media",true),
        new ResultPair("meet",true),
        new ResultPair("melbourne",true),
        new ResultPair("meme",true),
        new ResultPair("memorial",true),
        new ResultPair("men",true),
        new ResultPair("menu",true),
        new ResultPair("merckmsd",true),
        new ResultPair("metlife",true),
        new ResultPair("mg",true),
        new ResultPair("mh",true),
        new ResultPair("miami",true),
        new ResultPair("microsoft",true),
        new ResultPair("mil",true),
        new ResultPair("mini",true),
        new ResultPair("mint",true),
        new ResultPair("mit",true),
        new ResultPair("mitsubishi",true),
        new ResultPair("mk",true),
        new ResultPair("ml",true),
        new ResultPair("mlb",true),
        new ResultPair("mls",true),
        new ResultPair("mm",true),
        new ResultPair("mma",true),
        new ResultPair("mn",true),
        new ResultPair("mo",true),
        new ResultPair("mobi",true),
        new ResultPair("mobile",true),
        new ResultPair("mobily",true),
        new ResultPair("moda",true),
        new ResultPair("moe",true),
        new ResultPair("moi",true),
        new ResultPair("mom",true),
        new ResultPair("monash",true),
        new ResultPair("money",true),
        new ResultPair("monster",true),
        new ResultPair("mopar",true),
        new ResultPair("mormon",true),
        new ResultPair("mortgage",true),
        new ResultPair("moscow",true),
        new ResultPair("moto",true),
        new ResultPair("motorcycles",true),
        new ResultPair("mov",true),
        new ResultPair("movie",true),
        new ResultPair("movistar",true),
        new ResultPair("mp",true),
        new ResultPair("mq",true),
        new ResultPair("mr",true),
        new ResultPair("ms",true),
        new ResultPair("msd",true),
        new ResultPair("mt",true),
        new ResultPair("mtn",true),
        new ResultPair("mtr",true),
        new ResultPair("mu",true),
        new ResultPair("museum",true),
        new ResultPair("mutual",true),
        new ResultPair("mv",true),
        new ResultPair("mw",true),
        new ResultPair("mx",true),
        new ResultPair("my",true),
        new ResultPair("mz",true),
        new ResultPair("na",true),
        new ResultPair("nab",true),
        new ResultPair("nadex",true),
        new ResultPair("nagoya",true),
        new ResultPair("name",true),
        new ResultPair("nationwide",true),
        new ResultPair("natura",true),
        new ResultPair("navy",true),
        new ResultPair("nba",true),
        new ResultPair("nc",true),
        new ResultPair("ne",true),
        new ResultPair("nec",true),
        new ResultPair("net",true),
        new ResultPair("netbank",true),
        new ResultPair("netflix",true),
        new ResultPair("network",true),
        new ResultPair("neustar",true),
        new ResultPair("new",true),
        new ResultPair("newholland",true),
        new ResultPair("news",true),
        new ResultPair("next",true),
        new ResultPair("nextdirect",true),
        new ResultPair("nexus",true),
        new ResultPair("nf",true),
        new ResultPair("nfl",true),
        new ResultPair("ng",true),
        new ResultPair("ngo",true),
        new ResultPair("nhk",true),
        new ResultPair("ni",true),
        new ResultPair("nico",true),
        new ResultPair("nike",true),
        new ResultPair("nikon",true),
        new ResultPair("ninja",true),
        new ResultPair("nissan",true),
        new ResultPair("nissay",true),
        new ResultPair("nl",true),
        new ResultPair("no",true),
        new ResultPair("nokia",true),
        new ResultPair("northwesternmutual",true),
        new ResultPair("norton",true),
        new ResultPair("now",true),
        new ResultPair("nowruz",true),
        new ResultPair("nowtv",true),
        new ResultPair("np",true),
        new ResultPair("nr",true),
        new ResultPair("nra",true),
        new ResultPair("nrw",true),
        new ResultPair("ntt",true),
        new ResultPair("nu",true),
        new ResultPair("nyc",true),
        new ResultPair("nz",true),
        new ResultPair("obi",true),
        new ResultPair("observer",true),
        new ResultPair("off",true),
        new ResultPair("office",true),
        new ResultPair("okinawa",true),
        new ResultPair("olayan",true),
        new ResultPair("olayangroup",true),
        new ResultPair("oldnavy",true),
        new ResultPair("ollo",true),
        new ResultPair("om",true),
        new ResultPair("omega",true),
        new ResultPair("one",true),
        new ResultPair("ong",true),
        new ResultPair("onl",true),
        new ResultPair("online",true),
        new ResultPair("onyourside",true),
        new ResultPair("ooo",true),
        new ResultPair("open",true),
        new ResultPair("oracle",true),
        new ResultPair("orange",true),
        new ResultPair("org",true),
        new ResultPair("organic",true),
        new ResultPair("origins",true),
        new ResultPair("osaka",true),
        new ResultPair("otsuka",true),
        new ResultPair("ott",true),
        new ResultPair("ovh",true),
        new ResultPair("pa",true),
        new ResultPair("page",true),
        new ResultPair("panasonic",true),
        new ResultPair("paris",true),
        new ResultPair("pars",true),
        new ResultPair("partners",true),
        new ResultPair("parts",true),
        new ResultPair("party",true),
        new ResultPair("passagens",true),
        new ResultPair("pay",true),
        new ResultPair("pccw",true),
        new ResultPair("pe",true),
        new ResultPair("pet",true),
        new ResultPair("pf",true),
        new ResultPair("pfizer",true),
        new ResultPair("pg",true),
        new ResultPair("ph",true),
        new ResultPair("pharmacy",true),
        new ResultPair("phd",true),
        new ResultPair("philips",true),
        new ResultPair("phone",true),
        new ResultPair("photo",true),
        new ResultPair("photography",true),
        new ResultPair("photos",true),
        new ResultPair("physio",true),
        new ResultPair("piaget",true),
        new ResultPair("pics",true),
        new ResultPair("pictet",true),
        new ResultPair("pictures",true),
        new ResultPair("pid",true),
        new ResultPair("pin",true),
        new ResultPair("ping",true),
        new ResultPair("pink",true),
        new ResultPair("pioneer",true),
        new ResultPair("pizza",true),
        new ResultPair("pk",true),
        new ResultPair("pl",true),
        new ResultPair("place",true),
        new ResultPair("play",true),
        new ResultPair("playstation",true),
        new ResultPair("plumbing",true),
        new ResultPair("plus",true),
        new ResultPair("pm",true),
        new ResultPair("pn",true),
        new ResultPair("pnc",true),
        new ResultPair("pohl",true),
        new ResultPair("poker",true),
        new ResultPair("politie",true),
        new ResultPair("porn",true),
        new ResultPair("post",true),
        new ResultPair("pr",true),
        new ResultPair("pramerica",true),
        new ResultPair("praxi",true),
        new ResultPair("press",true),
        new ResultPair("prime",true),
        new ResultPair("pro",true),
        new ResultPair("prod",true),
        new ResultPair("productions",true),
        new ResultPair("prof",true),
        new ResultPair("progressive",true),
        new ResultPair("promo",true),
        new ResultPair("properties",true),
        new ResultPair("property",true),
        new ResultPair("protection",true),
        new ResultPair("pru",true),
        new ResultPair("prudential",true),
        new ResultPair("ps",true),
        new ResultPair("pt",true),
        new ResultPair("pub",true),
        new ResultPair("pw",true),
        new ResultPair("pwc",true),
        new ResultPair("py",true),
        new ResultPair("qa",true),
        new ResultPair("qpon",true),
        new ResultPair("quebec",true),
        new ResultPair("quest",true),
        new ResultPair("qvc",true),
        new ResultPair("racing",true),
        new ResultPair("radio",true),
        new ResultPair("raid",true),
        new ResultPair("re",true),
        new ResultPair("read",true),
        new ResultPair("realestate",true),
        new ResultPair("realtor",true),
        new ResultPair("realty",true),
        new ResultPair("recipes",true),
        new ResultPair("red",true),
        new ResultPair("redstone",true),
        new ResultPair("redumbrella",true),
        new ResultPair("rehab",true),
        new ResultPair("reise",true),
        new ResultPair("reisen",true),
        new ResultPair("reit",true),
        new ResultPair("reliance",true),
        new ResultPair("ren",true),
        new ResultPair("rent",true),
        new ResultPair("rentals",true),
        new ResultPair("repair",true),
        new ResultPair("report",true),
        new ResultPair("republican",true),
        new ResultPair("rest",true),
        new ResultPair("restaurant",true),
        new ResultPair("review",true),
        new ResultPair("reviews",true),
        new ResultPair("rexroth",true),
        new ResultPair("rich",true),
        new ResultPair("richardli",true),
        new ResultPair("ricoh",true),
        new ResultPair("rightathome",true),
        new ResultPair("ril",true),
        new ResultPair("rio",true),
        new ResultPair("rip",true),
        new ResultPair("rmit",true),
        new ResultPair("ro",true),
        new ResultPair("rocher",true),
        new ResultPair("rocks",true),
        new ResultPair("rodeo",true),
        new ResultPair("rogers",true),
        new ResultPair("room",true),
        new ResultPair("rs",true),
        new ResultPair("rsvp",true),
        new ResultPair("ru",true),
        new ResultPair("rugby",true),
        new ResultPair("ruhr",true),
        new ResultPair("run",true),
        new ResultPair("rw",true),
        new ResultPair("rwe",true),
        new ResultPair("ryukyu",true),
        new ResultPair("sa",true),
        new ResultPair("saarland",true),
        new ResultPair("safe",true),
        new ResultPair("safety",true),
        new ResultPair("sakura",true),
        new ResultPair("sale",true),
        new ResultPair("salon",true),
        new ResultPair("samsclub",true),
        new ResultPair("samsung",true),
        new ResultPair("sandvik",true),
        new ResultPair("sandvikcoromant",true),
        new ResultPair("sanofi",true),
        new ResultPair("sap",true),
        new ResultPair("sarl",true),
        new ResultPair("sas",true),
        new ResultPair("save",true),
        new ResultPair("saxo",true),
        new ResultPair("sb",true),
        new ResultPair("sbi",true),
        new ResultPair("sbs",true),
        new ResultPair("sc",true),
        new ResultPair("sca",true),
        new ResultPair("scb",true),
        new ResultPair("schaeffler",true),
        new ResultPair("schmidt",true),
        new ResultPair("scholarships",true),
        new ResultPair("school",true),
        new ResultPair("schule",true),
        new ResultPair("schwarz",true),
        new ResultPair("science",true),
        new ResultPair("scjohnson",true),
        new ResultPair("scor",true),
        new ResultPair("scot",true),
        new ResultPair("sd",true),
        new ResultPair("se",true),
        new ResultPair("search",true),
        new ResultPair("seat",true),
        new ResultPair("secure",true),
        new ResultPair("security",true),
        new ResultPair("seek",true),
        new ResultPair("select",true),
        new ResultPair("sener",true),
        new ResultPair("services",true),
        new ResultPair("ses",true),
        new ResultPair("seven",true),
        new ResultPair("sew",true),
        new ResultPair("sex",true),
        new ResultPair("sexy",true),
        new ResultPair("sfr",true),
        new ResultPair("sg",true),
        new ResultPair("sh",true),
        new ResultPair("shangrila",true),
        new ResultPair("sharp",true),
        new ResultPair("shaw",true),
        new ResultPair("shell",true),
        new ResultPair("shia",true),
        new ResultPair("shiksha",true),
        new ResultPair("shoes",true),
        new ResultPair("shop",true),
        new ResultPair("shopping",true),
        new ResultPair("shouji",true),
        new ResultPair("show",true),
        new ResultPair("showtime",true),
        new ResultPair("shriram",true),
        new ResultPair("si",true),
        new ResultPair("silk",true),
        new ResultPair("sina",true),
        new ResultPair("singles",true),
        new ResultPair("site",true),
        new ResultPair("sj",true),
        new ResultPair("sk",true),
        new ResultPair("ski",true),
        new ResultPair("skin",true),
        new ResultPair("sky",true),
        new ResultPair("skype",true),
        new ResultPair("sl",true),
        new ResultPair("sling",true),
        new ResultPair("sm",true),
        new ResultPair("smart",true),
        new ResultPair("smile",true),
        new ResultPair("sn",true),
        new ResultPair("sncf",true),
        new ResultPair("so",true),
        new ResultPair("soccer",true),
        new ResultPair("social",true),
        new ResultPair("softbank",true),
        new ResultPair("software",true),
        new ResultPair("sohu",true),
        new ResultPair("solar",true),
        new ResultPair("solutions",true),
        new ResultPair("song",true),
        new ResultPair("sony",true),
        new ResultPair("soy",true),
        new ResultPair("space",true),
        new ResultPair("spiegel",true),
        new ResultPair("sport",true),
        new ResultPair("spot",true),
        new ResultPair("spreadbetting",true),
        new ResultPair("sr",true),
        new ResultPair("srl",true),
        new ResultPair("srt",true),
        new ResultPair("st",true),
        new ResultPair("stada",true),
        new ResultPair("staples",true),
        new ResultPair("star",true),
        new ResultPair("starhub",true),
        new ResultPair("statebank",true),
        new ResultPair("statefarm",true),
        new ResultPair("stc",true),
        new ResultPair("stcgroup",true),
        new ResultPair("stockholm",true),
        new ResultPair("storage",true),
        new ResultPair("store",true),
        new ResultPair("stream",true),
        new ResultPair("studio",true),
        new ResultPair("study",true),
        new ResultPair("style",true),
        new ResultPair("su",true),
        new ResultPair("sucks",true),
        new ResultPair("supplies",true),
        new ResultPair("supply",true),
        new ResultPair("support",true),
        new ResultPair("surf",true),
        new ResultPair("surgery",true),
        new ResultPair("suzuki",true),
        new ResultPair("sv",true),
        new ResultPair("swatch",true),
        new ResultPair("swiftcover",true),
        new ResultPair("swiss",true),
        new ResultPair("sx",true),
        new ResultPair("sy",true),
        new ResultPair("sydney",true),
        new ResultPair("symantec",true),
        new ResultPair("systems",true),
        new ResultPair("sz",true),
        new ResultPair("tab",true),
        new ResultPair("taipei",true),
        new ResultPair("talk",true),
        new ResultPair("taobao",true),
        new ResultPair("target",true),
        new ResultPair("tatamotors",true),
        new ResultPair("tatar",true),
        new ResultPair("tattoo",true),
        new ResultPair("tax",true),
        new ResultPair("taxi",true),
        new ResultPair("tc",true),
        new ResultPair("tci",true),
        new ResultPair("td",true),
        new ResultPair("tdk",true),
        new ResultPair("team",true),
        new ResultPair("tech",true),
        new ResultPair("technology",true),
        new ResultPair("tel",true),
        new ResultPair("telefonica",true),
        new ResultPair("temasek",true),
        new ResultPair("tennis",true),
        new ResultPair("teva",true),
        new ResultPair("tf",true),
        new ResultPair("tg",true),
        new ResultPair("th",true),
        new ResultPair("thd",true),
        new ResultPair("theater",true),
        new ResultPair("theatre",true),
        new ResultPair("tiaa",true),
        new ResultPair("tickets",true),
        new ResultPair("tienda",true),
        new ResultPair("tiffany",true),
        new ResultPair("tips",true),
        new ResultPair("tires",true),
        new ResultPair("tirol",true),
        new ResultPair("tj",true),
        new ResultPair("tjmaxx",true),
        new ResultPair("tjx",true),
        new ResultPair("tk",true),
        new ResultPair("tkmaxx",true),
        new ResultPair("tl",true),
        new ResultPair("tm",true),
        new ResultPair("tmall",true),
        new ResultPair("tn",true),
        new ResultPair("to",true),
        new ResultPair("today",true),
        new ResultPair("tokyo",true),
        new ResultPair("tools",true),
        new ResultPair("top",true),
        new ResultPair("toray",true),
        new ResultPair("toshiba",true),
        new ResultPair("total",true),
        new ResultPair("tours",true),
        new ResultPair("town",true),
        new ResultPair("toyota",true),
        new ResultPair("toys",true),
        new ResultPair("tr",true),
        new ResultPair("trade",true),
        new ResultPair("trading",true),
        new ResultPair("training",true),
        new ResultPair("travel",true),
        new ResultPair("travelchannel",true),
        new ResultPair("travelers",true),
        new ResultPair("travelersinsurance",true),
        new ResultPair("trust",true),
        new ResultPair("trv",true),
        new ResultPair("tt",true),
        new ResultPair("tube",true),
        new ResultPair("tui",true),
        new ResultPair("tunes",true),
        new ResultPair("tushu",true),
        new ResultPair("tv",true),
        new ResultPair("tvs",true),
        new ResultPair("tw",true),
        new ResultPair("tz",true),
        new ResultPair("ua",true),
        new ResultPair("ubank",true),
        new ResultPair("ubs",true),
        new ResultPair("uconnect",true),
        new ResultPair("ug",true),
        new ResultPair("uk",true),
        new ResultPair("unicom",true),
        new ResultPair("university",true),
        new ResultPair("uno",true),
        new ResultPair("uol",true),
        new ResultPair("ups",true),
        new ResultPair("us",true),
        new ResultPair("uy",true),
        new ResultPair("uz",true),
        new ResultPair("va",true),
        new ResultPair("vacations",true),
        new ResultPair("vana",true),
        new ResultPair("vanguard",true),
        new ResultPair("vc",true),
        new ResultPair("ve",true),
        new ResultPair("vegas",true),
        new ResultPair("ventures",true),
        new ResultPair("verisign",true),
        new ResultPair("versicherung",true),
        new ResultPair("vet",true),
        new ResultPair("vg",true),
        new ResultPair("vi",true),
        new ResultPair("viajes",true),
        new ResultPair("video",true),
        new ResultPair("vig",true),
        new ResultPair("viking",true),
        new ResultPair("villas",true),
        new ResultPair("vin",true),
        new ResultPair("vip",true),
        new ResultPair("virgin",true),
        new ResultPair("visa",true),
        new ResultPair("vision",true),
        new ResultPair("vistaprint",true),
        new ResultPair("viva",true),
        new ResultPair("vivo",true),
        new ResultPair("vlaanderen",true),
        new ResultPair("vn",true),
        new ResultPair("vodka",true),
        new ResultPair("volkswagen",true),
        new ResultPair("volvo",true),
        new ResultPair("vote",true),
        new ResultPair("voting",true),
        new ResultPair("voto",true),
        new ResultPair("voyage",true),
        new ResultPair("vu",true),
        new ResultPair("vuelos",true),
        new ResultPair("wales",true),
        new ResultPair("walmart",true),
        new ResultPair("walter",true),
        new ResultPair("wang",true),
        new ResultPair("wanggou",true),
        new ResultPair("warman",true),
        new ResultPair("watch",true),
        new ResultPair("watches",true),
        new ResultPair("weather",true),
        new ResultPair("weatherchannel",true),
        new ResultPair("webcam",true),
        new ResultPair("weber",true),
        new ResultPair("website",true),
        new ResultPair("wed",true),
        new ResultPair("wedding",true),
        new ResultPair("weibo",true),
        new ResultPair("weir",true),
        new ResultPair("wf",true),
        new ResultPair("whoswho",true),
        new ResultPair("wien",true),
        new ResultPair("wiki",true),
        new ResultPair("williamhill",true),
        new ResultPair("win",true),
        new ResultPair("windows",true),
        new ResultPair("wine",true),
        new ResultPair("winners",true),
        new ResultPair("wme",true),
        new ResultPair("wolterskluwer",true),
        new ResultPair("woodside",true),
        new ResultPair("work",true),
        new ResultPair("works",true),
        new ResultPair("world",true),
        new ResultPair("wow",true),
        new ResultPair("ws",true),
        new ResultPair("wtc",true),
        new ResultPair("wtf",true),
        new ResultPair("xbox",true),
        new ResultPair("xerox",true),
        new ResultPair("xfinity",true),
        new ResultPair("xihuan",true),
        new ResultPair("xin",true),
        new ResultPair("xn--11b4c3d",true),
        new ResultPair("xn--1ck2e1b",true),
        new ResultPair("xn--1qqw23a",true),
        new ResultPair("xn--2scrj9c",true),
        new ResultPair("xn--30rr7y",true),
        new ResultPair("xn--3bst00m",true),
        new ResultPair("xn--3ds443g",true),
        new ResultPair("xn--3e0b707e",true),
        new ResultPair("xn--3hcrj9c",true),
        new ResultPair("xn--3oq18vl8pn36a",true),
        new ResultPair("xn--3pxu8k",true),
        new ResultPair("xn--42c2d9a",true),
        new ResultPair("xn--45br5cyl",true),
        new ResultPair("xn--45brj9c",true),
        new ResultPair("xn--45q11c",true),
        new ResultPair("xn--4gbrim",true),
        new ResultPair("xn--54b7fta0cc",true),
        new ResultPair("xn--55qw42g",true),
        new ResultPair("xn--55qx5d",true),
        new ResultPair("xn--5su34j936bgsg",true),
        new ResultPair("xn--5tzm5g",true),
        new ResultPair("xn--6frz82g",true),
        new ResultPair("xn--6qq986b3xl",true),
        new ResultPair("xn--80adxhks",true),
        new ResultPair("xn--80ao21a",true),
        new ResultPair("xn--80aqecdr1a",true),
        new ResultPair("xn--80asehdb",true),
        new ResultPair("xn--80aswg",true),
        new ResultPair("xn--8y0a063a",true),
        new ResultPair("xn--90a3ac",true),
        new ResultPair("xn--90ae",true),
        new ResultPair("xn--90ais",true),
        new ResultPair("xn--9dbq2a",true),
        new ResultPair("xn--9et52u",true),
        new ResultPair("xn--9krt00a",true),
        new ResultPair("xn--b4w605ferd",true),
        new ResultPair("xn--bck1b9a5dre4c",true),
        new ResultPair("xn--c1avg",true),
        new ResultPair("xn--c2br7g",true),
        new ResultPair("xn--cck2b3b",true),
        new ResultPair("xn--cg4bki",true),
        new ResultPair("xn--clchc0ea0b2g2a9gcd",true),
        new ResultPair("xn--czr694b",true),
        new ResultPair("xn--czrs0t",true),
        new ResultPair("xn--czru2d",true),
        new ResultPair("xn--d1acj3b",true),
        new ResultPair("xn--d1alf",true),
        new ResultPair("xn--e1a4c",true),
        new ResultPair("xn--eckvdtc9d",true),
        new ResultPair("xn--efvy88h",true),
        new ResultPair("xn--estv75g",true),
        new ResultPair("xn--fct429k",true),
        new ResultPair("xn--fhbei",true),
        new ResultPair("xn--fiq228c5hs",true),
        new ResultPair("xn--fiq64b",true),
        new ResultPair("xn--fiqs8s",true),
        new ResultPair("xn--fiqz9s",true),
        new ResultPair("xn--fjq720a",true),
        new ResultPair("xn--flw351e",true),
        new ResultPair("xn--fpcrj9c3d",true),
        new ResultPair("xn--fzc2c9e2c",true),
        new ResultPair("xn--fzys8d69uvgm",true),
        new ResultPair("xn--g2xx48c",true),
        new ResultPair("xn--gckr3f0f",true),
        new ResultPair("xn--gecrj9c",true),
        new ResultPair("xn--gk3at1e",true),
        new ResultPair("xn--h2breg3eve",true),
        new ResultPair("xn--h2brj9c",true),
        new ResultPair("xn--h2brj9c8c",true),
        new ResultPair("xn--hxt814e",true),
        new ResultPair("xn--i1b6b1a6a2e",true),
        new ResultPair("xn--imr513n",true),
        new ResultPair("xn--io0a7i",true),
        new ResultPair("xn--j1aef",true),
        new ResultPair("xn--j1amh",true),
        new ResultPair("xn--j6w193g",true),
        new ResultPair("xn--jlq61u9w7b",true),
        new ResultPair("xn--jvr189m",true),
        new ResultPair("xn--kcrx77d1x4a",true),
        new ResultPair("xn--kprw13d",true),
        new ResultPair("xn--kpry57d",true),
        new ResultPair("xn--kpu716f",true),
        new ResultPair("xn--kput3i",true),
        new ResultPair("xn--l1acc",true),
        new ResultPair("xn--lgbbat1ad8j",true),
        new ResultPair("xn--mgb9awbf",true),
        new ResultPair("xn--mgba3a3ejt",true),
        new ResultPair("xn--mgba3a4f16a",true),
        new ResultPair("xn--mgba7c0bbn0a",true),
        new ResultPair("xn--mgbaakc7dvf",true),
        new ResultPair("xn--mgbaam7a8h",true),
        new ResultPair("xn--mgbab2bd",true),
        new ResultPair("xn--mgbai9azgqp6j",true),
        new ResultPair("xn--mgbayh7gpa",true),
        new ResultPair("xn--mgbb9fbpob",true),
        new ResultPair("xn--mgbbh1a",true),
        new ResultPair("xn--mgbbh1a71e",true),
        new ResultPair("xn--mgbc0a9azcg",true),
        new ResultPair("xn--mgbca7dzdo",true),
        new ResultPair("xn--mgberp4a5d4ar",true),
        new ResultPair("xn--mgbgu82a",true),
        new ResultPair("xn--mgbi4ecexp",true),
        new ResultPair("xn--mgbpl2fh",true),
        new ResultPair("xn--mgbt3dhd",true),
        new ResultPair("xn--mgbtx2b",true),
        new ResultPair("xn--mgbx4cd0ab",true),
        new ResultPair("xn--mix891f",true),
        new ResultPair("xn--mk1bu44c",true),
        new ResultPair("xn--mxtq1m",true),
        new ResultPair("xn--ngbc5azd",true),
        new ResultPair("xn--ngbe9e0a",true),
        new ResultPair("xn--ngbrx",true),
        new ResultPair("xn--node",true),
        new ResultPair("xn--nqv7f",true),
        new ResultPair("xn--nqv7fs00ema",true),
        new ResultPair("xn--nyqy26a",true),
        new ResultPair("xn--o3cw4h",true),
        new ResultPair("xn--ogbpf8fl",true),
        new ResultPair("xn--otu796d",true),
        new ResultPair("xn--p1acf",true),
        new ResultPair("xn--p1ai",true),
        new ResultPair("xn--pbt977c",true),
        new ResultPair("xn--pgbs0dh",true),
        new ResultPair("xn--pssy2u",true),
        new ResultPair("xn--q9jyb4c",true),
        new ResultPair("xn--qcka1pmc",true),
        new ResultPair("xn--qxam",true),
        new ResultPair("xn--rhqv96g",true),
        new ResultPair("xn--rovu88b",true),
        new ResultPair("xn--rvc1e0am3e",true),
        new ResultPair("xn--s9brj9c",true),
        new ResultPair("xn--ses554g",true),
        new ResultPair("xn--t60b56a",true),
        new ResultPair("xn--tckwe",true),
        new ResultPair("xn--tiq49xqyj",true),
        new ResultPair("xn--unup4y",true),
        new ResultPair("xn--vermgensberater-ctb",true),
        new ResultPair("xn--vermgensberatung-pwb",true),
        new ResultPair("xn--vhquv",true),
        new ResultPair("xn--vuq861b",true),
        new ResultPair("xn--w4r85el8fhu5dnra",true),
        new ResultPair("xn--w4rs40l",true),
        new ResultPair("xn--wgbh1c",true),
        new ResultPair("xn--wgbl6a",true),
        new ResultPair("xn--xhq521b",true),
        new ResultPair("xn--xkc2al3hye2a",true),
        new ResultPair("xn--xkc2dl3a5ee0h",true),
        new ResultPair("xn--y9a3aq",true),
        new ResultPair("xn--yfro4i67o",true),
        new ResultPair("xn--ygbi2ammx",true),
        new ResultPair("xn--zfr164b",true),
        new ResultPair("xxx",true),
        new ResultPair("xyz",true),
        new ResultPair("yachts",true),
        new ResultPair("yahoo",true),
        new ResultPair("yamaxun",true),
        new ResultPair("yandex",true),
        new ResultPair("ye",true),
        new ResultPair("yodobashi",true),
        new ResultPair("yoga",true),
        new ResultPair("yokohama",true),
        new ResultPair("you",true),
        new ResultPair("youtube",true),
        new ResultPair("yt",true),
        new ResultPair("yun",true),
        new ResultPair("za",true),
        new ResultPair("zappos",true),
        new ResultPair("zara",true),
        new ResultPair("zero",true),
        new ResultPair("zip",true),
        new ResultPair("zippo",true),
        new ResultPair("zm",true),
        new ResultPair("zone",true),
        new ResultPair("zuerich",true),
        new ResultPair("zw",true),
   };
}

